server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
okta:
  oauth2:
    issuer: https://dev-581373.okta.com/oauth2/default
    client-id: 0oam4f1f1ZlOTdTaC4x6
    client-secret: k89aAn91pdSHTZYJvgUYxACTgMKMbcXqbThJtjv7
logging:
  level:
    org:
      springframework:
        security: DEBUG

#
#
#  debug:
#    request: true
#
#zuul:
#  prefix:  /api
#  routes:
#    organizationservice: /organization/**
#    licensingservice: /licensing/**

